FROM nginx:1.27-alpine

WORKDIR /usr/share/nginx/html

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY index.html ./
COPY driver ./driver
COPY admin ./admin
COPY assets ./assets
COPY src ./src

EXPOSE 80
